name: dart_pokemon_server
description: dart_pokemon_server
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^2.17.5

dependencies:
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  dart_pokemon_core:
    git:
      url: https://github.com/mthsena/dart_pokemon_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
